logsBucket: "gs://calendar-events-creation-logs-bucket"
steps:
  # Steps to deploy functions
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - function-google-calendar-event-creation
      - --entry-point=create_new_events
      - --region=europe-west1	
      - --source=./gcloud/gcloud_functions
      - --trigger-http
      - --runtime=python312
      - --set-env-vars=SOURCE_FILE_URL="https://docs.google.com/spreadsheets/d/1GvAwkCIMPoSAxbfsCbLblEVp0E5CeFw6/edit?usp=sharing&ouid=117563738823996926338&rtpof=true&sd=true"