logsBucket: "gs://calendar-events-creation-logs-bucket"
steps:
  # Step to create a logging sink
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: 'bash'
    args:
      - -c
      - |
        if ! gcloud logging sinks create my-log-sink storage.googleapis.com/calendar-events-creation-logs-bucket \
          --log-filter='resource.type="cloud_function" AND resource.labels.function_name="function-google-calendar-event-creation"' \
          --project=sinuous-tuner-428711-f2
        SERVICE_ACCOUNT=$(gcloud logging sinks describe my-log-sink --format='value(writerIdentity)' --project=sinuous-tuner-428711-f2)
        gsutil iam ch ${SERVICE_ACCOUNT}:objectCreator gs://calendar-events-creation-logs-bucket
        else
          echo "Sink my-log-sink already exists, skipping creation."
        fi
  # Steps to deploy functions
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - function-google-calendar-event-creation
      - --entry-point=create_new_events
      - --region=europe-west1	
      - --source=./gcloud/gcloud_functions
      - --trigger-http
      - --runtime=python312
      - --memory=1GB
      - --set-env-vars=SOURCE_FILE_URL=https://docs.google.com/spreadsheets/d/1GvAwkCIMPoSAxbfsCbLblEVp0E5CeFw6/export?format=xlsx
  # Step to deploy the Cloud Workflows
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: 'gcloud'
    args:
      - workflows
      - deploy
      - workflow-google-calendar-events
      - --source=workflows/workflow-google-calendar-events.yaml
      - --location=europe-west1
