logsBucket: "gs://calendar-events-creation-logs-bucket"
steps:
  # Steps to deploy create reminder function and workflow
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - function-check-new-events-make-reminders
      - --entry-point=create_new_events
      - --region=europe-west1	
      - --source=./gcloud/gcloud_functions
      - --trigger-http
      - --runtime=python312
      - --memory=1GB
      - --set-env-vars=PROJECT_ID=481715545022,SECRET_ID=google-calendar-key,SMTP_CONFIG_SECRET=smtp_config,TARGET_CALENDAR_ID=kontakt@mieszkomotors.com,SOURCE_FILE_URL=https://docs.google.com/spreadsheets/d/1BmQecxZDzY-DZA70j52JPnu-yF2QfIOc1yxjq5nAFBI/export?format=xlsx
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: 'gcloud'
    args:
      - workflows
      - deploy
      - workflow-google-calendar-events
      - --source=workflows/workflow-google-calendar-events.yaml
      - --location=europe-west1
  #  # Steps to deploy refreshing secrets function and workflow 
  # - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  #   entrypoint: 'gcloud'
  #   args:
  #     - workflows
  #     - deploy
  #     - workflow-refresh-secrets
  #     - --source=workflows/workflow-refresh-secrets.yaml
  #     - --location=europe-west1
  # - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  #   args:
  #     - gcloud
  #     - functions
  #     - deploy
  #     - function-refresh-secrets
  #     - --entry-point=refresh_secrets
  #     - --region=europe-west1
  #     - --source=./gcloud/gcloud_functions
  #     - --trigger-http
  #     - --runtime=python312
  #     - --memory=1GB  
  #     - --set-env-vars=PROJECT_ID=481715545022,SECRET_ID=google-calendar-key
